### ISSUE TITLE
Bug: mismatching version in description / yarn.lock / title

### ISSUE THREAD

**Issue by danielma** [planningcenter/pco-release-action#26]
![CleanShot 2024-09-23 at 15 52 46@2x](https://github.com/user-attachments/assets/c1e0ca6d-4446-4781-a2d1-4635792eba4e)

This PR upgrades add-ons to 5.4.0 and says that in the title, but the description says it's upgrading to **both** 5.9.0 and 5.4.0. I have done no research at this time to understand how or why this happened. I am only logging that it appears to be a bug

https://github.com/planningcenter/topbar/pull/440

**Comment by kylemellander** [comment]
So, in researching this, I was able to discover that v5.4.0 was the last version of add-ons that allowed for [tapestry-react <4.3.1 as a peerDependency](https://github.com/planningcenter/add-ons-js/commit/335dc169d5af0bb21007c97badf79a766c4ee2e4#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R49).  Since `topbar` had the requirement of `tapestry-react` at `^4.3.0`, this did not satisfy the requirement and thus the newer versions were found to not be 100% compatible.

The specific example fix here is to raise the requirement in topbar for `tapestry-react`, but I think there is a reason to raise an error if the updating version does not match the desired version.
